### ISSUE TITLE
How to implement logical cluster？

### ISSUE THREAD

**Issue by haiertashu** [radondb/radondb-clickhouse-operator#9]
Hi All，
I saw the feature about **`logical cluster`** has already implemented in the [`Release Notes v2.0.0`](https://github.com/radondb/radondb-clickhouse-operator/releases/tag/chronus-2.0), but I found no idea about the details of the implements from the source code in file `ch_config_generator.go`:
```func (c *ClickHouseConfigGenerator) GetRemoteServers(options *RemoteServersGeneratorOptions) string {```

Could you tell me how the **`logical cluster`** comes true?
Thanks!

**Comment by su-houzhen** [comment]
In clickhouse, there are two cluster implementations:
1. Logical consistency cluster: by `distributed + mergetree` engine. This method does not rely on zookeeper, and the data writing of the replica is led by the distributed engine;
2. Physically consistent cluster: by `distributed + replicatedmergetree` engine. This method relies on zookeeper for data synchronization between replicas;

You can see the difference between these two clusters in the configuration file. The `internal_replication` of the logical consistency cluster is false, and the `internal_replication` of the physical consistency cluster is true;
